sonar.projectKey=Jonathangadeaharder_cargo-test-lint
sonar.organization=jonathangadeaharder

sonar.host.url=https://sonarcloud.io

sonar.sources=crates/
sonar.sourceEncoding=UTF-8
sonar.language=rust
sonar.rust.clippy.reportPaths=clippy_report.json

sonar.exclusions=target/**,**/fixtures/**,**/benches/**

sonar.coverage.exclusions=**/fixtures/**,**/benches/**

sonar.cpd.exclusions=target/**,**/fixtures/**
