sonar.projectKey=VidiomTM_cargo-test-lint
sonar.organization=VidiomTM

sonar.host.url=https://sonarcloud.io

sonar.sources=crates/
sonar.tests=crates/
sonar.sourceEncoding=UTF-8
sonar.language=rust
sonar.rust.clippy.reportPaths=clippy_report.json

sonar.exclusions=target/**,**/fixtures/**,**/tests/**

sonar.coverage.exclusions=**/tests/**,**/fixtures/**,**/benches/**

sonar.cpd.exclusions=target/**,**/fixtures/**
